
name = "blog"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2025-05-23"
routes = [
  { pattern = "powerfultraveling.com", custom_domain = true }
]

[site]
bucket = ".output/public"

